stages:
  data_ingestion:
    cmd: python src/foodhealthclassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/foodhealthclassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion

  data_validation:
    cmd: python src/foodhealthclassifier/pipeline/stage_02_data_validation.py
    deps:
      - src/foodhealthclassifier/pipeline/stage_02_data_validation.py
      - config/config.yaml
    outs:
      - artifacts/data_validation

  data_transformation:
    cmd: python src/foodhealthclassifier/pipeline/stage_03_data_transformation.py
    deps:
      - src/foodhealthclassifier/pipeline/stage_03_data_transformation.py
      - config/config.yaml
    outs:
      - artifacts/data_transformation

  model_trainer:
    cmd: python src/foodhealthclassifier/pipeline/stage_04_model_trainer.py
    deps: 
      - src/foodhealthclassifier/pipeline/stage_04_model_trainer.py
      - config/config.yaml
    outs:
      - artifacts/model_trainer/foodhealth_classifier.pkl
